<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
	public function myFindAll()
	{
		// méthode 1 -> par l'EntityManager
		$queryBuilder = $this->_em->createQueryBuilder()->select('a')->from($this->_entityName, 'a');

		// méthode 2 -> par le raccourci
		$queryBuilder = $this->createQueryBuilder('a');

		$query = $queryBuilder->getQuery();
		$results = $query->getResult();

		return $results;
	}

	public function myFindOne($id)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->where('a.id = :id')->setParameter('id', $id);

		return $qb->getQuery()->getSingleResult();
	}

	public function whereCurrentYear(QueryBuilder $qb)
	{
		$qb
		  ->andWhere('a.date BETWEEN :start AND :end')
		  ->setParameter('start', new \Datetime(date('Y').'-01-01'))
		  ->setParameter('end', new \Datetime(date('Y').'-12-31'));
	}

	public function myFind()
	{
		$qb = $this->createQueryBuilder('a');
		$qb->where('a.author = :author')->setParameter('author', 'Marine');

		$this->whereCurrentYear($qb);

		$qb->orderBy('a.date', 'DESC');

		return $qb->getQuery()->getResult();
	}

	public function getAdvertWithApplications()
	{
		$qb = $this->createQueryBuilder('a')
			->leftJoin('a.applications', 'app')
			->addSelect('app');

		return $qb->getQuery()->getResult();
	}

	public function getAdvertWithCategories(array $categoryName)
	{
		$qb = $this->createQueryBuilder('a')
			->innerJoin('a.categories', 'cat')
			->addSelect('cat');

		$qb->where($qb->expr()->in('cat.name', $categoryName));
		return $qb->getQuery()->getResult();
	}
}
