<?php

namespace OC\PlatformBundle\Repository;

/**
 * ImageEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
